name: admin-ui-context
namespace: official
version: 1.0.0
author: Wazo Team
display_name: Context
min_wazo_version: 17.16
tags:
  - beta
  - internal
homepage: https://github.com/wazo-pbx/wazo-admin-ui-context
