plugin_format_version: 2
name: admin-ui-context
namespace: official
version: 1.1.1-2
author: Wazo Team
display_name: Context
min_wazo_version: 18.02
tags:
  - internal
homepage: https://github.com/wazo-pbx/wazo-admin-ui-context
