name: admin-ui-context
namespace: official
version: 1.1.1-1
author: Wazo Team
display_name: Context
min_wazo_version: 18.01
tags:
  - beta
  - internal
homepage: https://github.com/wazo-pbx/wazo-admin-ui-context
